### ISSUE TITLE
error decode response: invalid character 'x' in string escape code

### ISSUE THREAD

**Issue by Proxymiity** [VictoriaMetrics/victorialogs-datasource#24] opened 2024-06-11 12:58 UTC
Hi,

When using the latest version of VictoriaLogs (0.18.0 as of today, after upgrading from 0.7.0), the datasource stops working.
A simple `_time:5m` or `host:test-server` returns a decoding error in the panel: `error decode response: invalid character 'x' in string escape code`

No specific error logged in the VictoriaLogs server itself, but the Grafana log has some errors:
```
GRAFANA  | logger=plugin.victorialogs-datasource t=2024-06-11T12:50:04.627607298Z level=error msg="error decode response: invalid character 'x' in string escape code"
GRAFANA  | logger=context userId=2 orgId=1 uname=*** t=2024-06-11T12:50:04.627862706Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=*** time_ms=105 duration=105.622792ms size=139 referer="http://***/d/bdoghm58zwdmof/test-panel?editPanel=2&orgId=1" handler=/api/ds/query status_source=downstream
```

The query itself works fine in the vmui. Datasource is on 0.2.1, and when added replies with "This datasource is working".
Rolling back to our known working vlogs version (0.7.0) works well, however we lose new features of the query language.

**Comment by hagen1778** [comment] 2024-06-24 09:06
@dmitryk-dk is this related to the backend of the plugin?

**Comment by dmitryk-dk** [comment] 2024-06-24 09:40
Hi @Proxymiity ! Can you share what version of the VictoriaLogs you have?  Can you share an example of your response from the VMUI you have? 
This information can help us to detect the problem

**Comment by dmitryk-dk** [comment] 2024-06-26 13:46
> FYI, I have a working panel with that version. Some are returning "no data" because there is no data in the timerange (which is expected), one is returning data correctly, and some are erroring with the same error you'd find within the first issue comment

It would be helpful if you could share the response in JSON and remove sensitive data. 
I will try to reproduce the issue. There are used standard JSON decoders, and I think the problem is with parsing response from the victoria logs. 
But it is only my assumption

**Comment by Proxymiity** [comment] 2024-06-26 15:05
> It would be helpful if you could share the response in JSON and remove sensitive data when you get that error. I will try to reproduce the issue. There are used standard JSON decoders, and I think the problem is with parsing response from the victoria logs. But it is only my assumption

By response, do you mean intercept the response from VLogs back to Grafana?

**Comment by dmitryk-dk** [comment] 2024-06-26 15:44
> > It would be helpful if you could share the response in JSON and remove sensitive data when you get that error. I will try to reproduce the issue. There are used standard JSON decoders, and I think the problem is with parsing response from the victoria logs. But it is only my assumption
> 
> By response, do you mean intercept the response from VLogs back to Grafana?

Yes, or response from vmlogs to vmui. They should be identical.

**Comment by Proxymiity** [comment] 2024-06-27 08:13
Here are the responses from both VictoriaLogs versions (mind the dot at the end of the url):
0.7.0: https://m.iya.at/hLfWw.
0.21.0: https://m.iya.at/hHZ76.

**Comment by dmitryk-dk** [comment] 2024-06-27 16:34
> Here are the responses from both VictoriaLogs versions (mind the dot at the end of the url): 0.7.0: https://m.iya.at/hLfWw. 0.21.0: https://m.iya.at/hHZ76.

Thank you for providing examples. I will check it soon

**Comment by dmitryk-dk** [comment] 2024-07-02 15:09
Hi @Proxymiity , I think I found the problem and made a draft fix; if you can build a source from my PR and test it, that would be great. I will check the fix on my own

**Comment by Proxymiity** [comment] 2024-07-02 17:08
> Hi @Proxymiity , I think I found the problem and made a draft fix; if you can build a source from my PR and test it, that would be great. I will check the fix on my own

Hi, thanks for the quick draft. I will look into building the plugin and will keep you informed.

**Comment by Proxymiity** [comment] 2024-07-04 09:26
Hi, just compiled and tested your fix. It does not error out anymore, but instead the color has vanished.

Here's vlogs 0.27.0 and your patch:
![image](https://github.com/VictoriaMetrics/victorialogs-datasource/assets/25194496/bf3ca104-2615-4ab6-8f7e-789f6f5aece8)

Here's vlogs 0.7.0 and your patch:
![image](https://github.com/VictoriaMetrics/victorialogs-datasource/assets/25194496/e8c89fc0-526a-41c6-882f-3965e7466257)

**Comment by dmitryk-dk** [comment] 2024-07-04 15:36
@Proxymiity, the logs sent from vlogs only proxied to the UI part of the data source, I will think about how it is better to handle those values with colors. I think it should be handle on the UI part of the plugin @Loori-R , @hagen1778 wdyt?

**Comment by valyala** [comment] 2024-07-05 00:16
This issue must be fixed in [VictoriaLogs v0.27.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.27.1-victorialogs). The bugfix is at https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c0caa6993903a748c8942c8c28b5901ee6d5f4d4 .

@Proxymiity , @rkaracic , could you upgrade VictoriaLogs to [v0.27.1](https://docs.victoriametrics.com/victorialogs/changelog/) and verify whether the issue is fixed there?

**Comment by clrxbl** [comment] 2024-07-05 00:52
> This issue must be fixed in [VictoriaLogs v0.27.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.27.1-victorialogs). The bugfix is at [VictoriaMetrics/VictoriaMetrics@c0caa69](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c0caa6993903a748c8942c8c28b5901ee6d5f4d4) .
> 
> @Proxymiity , @rkaracic , could you upgrade VictoriaLogs to [v0.27.1](https://docs.victoriametrics.com/victorialogs/changelog/) and verify whether the issue is fixed there?

I've had this issue aswell but after upgrading to 0.27.1, it went away.

**Comment by rkaracic** [comment] 2024-07-05 06:53
I can confirm that issue is gone in 0.27.1

**Comment by hagen1778** [comment] 2024-07-05 09:20
The problem was fixed on the backend side by VictoriaLogs.
Additionally, plugin now understands unicode and ANSI chars thanks to https://github.com/VictoriaMetrics/victorialogs-datasource/pull/38.

**Comment by dmitryk-dk** [comment] 2024-07-08 11:28
Hi! The issue was fixed by two separate improvement for VictoriaLogs itself and in the datasource.

Please check the [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.2.4). 
Close issue as resolved.

**Closed by dmitryk-dk** 2024-07-08 11:28 UTC
Labels: bug, waiting for release

**Comment by Proxymiity** [comment] 2024-07-09 13:07
Hi! Apologies for the response delay.

I can confirm it is working as expected as of the latest version of vlogs and the patch you made.

Thank you!
