### ISSUE TITLE
Time range ignored

### ISSUE THREAD

**Issue by TertiumOrganum1** [VictoriaMetrics/victorialogs-datasource#12] opened 2024-03-10 00:05 UTC
Sometimes source refused to take time range into account, especially when specify particular range boundaries (not 'now'). Behavior remain even after ctrl+shift+r.
I found a correlation - this happens when I specify time values as From and To and add non-msg field in query:
_stream:{service=gateway,level=error,status=408} ingest_timestamp:*

![image](https://github.com/VictoriaMetrics/victorialogs-datasource/assets/51286827/bbb203b9-bb9c-4390-9d10-5ebd7c4fc62a)

**Comment by Loori-R** [comment] 2024-03-10 13:53
Could you wrap the query in parentheses and check if the time filter is applied correctly to ensure the issue is related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5920:
`(_stream:{service=gateway,level=error,status=408} ingest_timestamp:*)`

**Comment by TertiumOrganum1** [comment] 2024-03-11 09:55
this behaviour is not stable, but I'll try next time

вс, 10 мар. 2024 г., 16:53 Yury Molodov ***@***.***>:

**Comment by dmitryk-dk** [comment] 2024-04-01 08:54
This bug has been fixed in [v0.2.0 release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.2.0). Closing the issue as fixed then.

**Closed by dmitryk-dk** 2024-04-01 08:54 UTC
Labels: bug
