### ISSUE TITLE
Submit victorialogs datasource to Grafana's plugin marketplace

### ISSUE THREAD

**Issue by geekflyer** [VictoriaMetrics/victorialogs-datasource#51] opened 2024-07-22 09:16 UTC
Hi,

would love to try out victorialogs a bit more and use it alongside our existing logging solution.
That said in order to do that effectively I'd need to use the datasource in Grafana Cloud, which doesn't allow sideloading unsigned plugins.

Any timeline / estimates on when you are planning to do that?

**Comment by dmitryk-dk** [comment] 2024-07-22 09:30
Hi @geekflyer ! You can check a similar question for victoriametrics-datasource. I hope it will help you
https://github.com/VictoriaMetrics/victoriametrics-datasource/issues/87

**Comment by vitaliy-sk** [comment] 2024-11-19 23:12
+1 
unfortunately grafana cloud not support unsigned plugins

**Comment by Loori-R** [comment] 2024-12-05 23:13
Duplicate of #127. Please follow updates there.

**Closed by Loori-R** 2024-12-05 23:13 UTC
Labels: enhancement
