### ISSUE TITLE
How to support mulit options with label values of stream-fields

### ISSUE THREAD

**Issue by worker24h** [VictoriaMetrics/victorialogs-datasource#109] opened 2024-11-20 09:34 UTC
![image](https://github.com/user-attachments/assets/05403772-a77b-4f9f-87cc-50e03370aba1)

When I selected `ALL`,  the result of query is nothing, as follows:
![image](https://github.com/user-attachments/assets/152edc5e-d218-4558-bc06-73984e319f21)

So I capture the package of http：
```json
{
  "from": xxx
  "to": xxx
   "queries":  {
     ...
     "expr": "{pod=~\"(neolix-cockpit-server-5888c774f-fqrgv OR neolix-cockpit-server-5888c774f-smclh)\",container_name=\"neolix-cockpit-server\",namespace=\"vehicle-platform\"} MarsSendServiceImpl",
     ...
    }
}
```
The LogQL is : `{pod=~"${pod}",container_name="${container}",namespace="${namespace}"} ${query}`

The value of variable pod is generated by grafana auto, But, **I think the victorialogs does not support it**, which it is `(AAA OR BBB)`

so, how to fix it?  Everyone, thanks 

@hagen1778 @dmitryk-dk

**Comment by hagen1778** [comment] 2024-11-21 09:37
Hey @worker24h !
Have you tried set All value to `*`? 
See my example for `host` variable below:
<img width="518" alt="image" src="https://github.com/user-attachments/assets/6da7386f-9fbd-437e-9126-e2da3a07ff7c">

And then on query time:
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/6570cf0b-cf78-4f5d-9282-d0a15fe2cc62">

And here's how it works for `All`:
<img width="404" alt="image" src="https://github.com/user-attachments/assets/41f4c606-00df-44cc-bb8a-ee5188dcf8b0">

**Comment by worker24h** [comment] 2024-11-21 10:48
Yes, your case is done, but my case is stream field. When  I setted `*` , it response failed.
![image](https://github.com/user-attachments/assets/5212fe0f-5400-48d3-9dd5-886bdbb38003)

The fields of stream, as follows
![image](https://github.com/user-attachments/assets/c08332ed-c65f-453c-a2b4-e829343854d9)

@hagen1778

**Comment by hagen1778** [comment] 2024-11-21 11:44
Try changing `*` to `.*` in All options settings for variable

**Comment by worker24h** [comment] 2024-11-21 12:18
> Try changing `*` to `.*` in All options settings for variable

Perfect, `.*` for 'ALL' is good.  **But,** if selected two items, the result of query is nothing.  So I think,  it will be fixed.

![image](https://github.com/user-attachments/assets/935840ad-b5bd-4d98-94d3-ea0a8ce81b45)

**Comment by Loori-R** [comment] 2024-11-21 13:12
Yes, of course, I'll see what I can do.

**Comment by dmitryk-dk** [comment] 2024-12-04 17:16
Hi @worker24h ! The issue was fixed in the new plugin [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.10.0). Close this issue as resolved. Feel free to reopen the issue if you find any problems.

**Comment by hagen1778** [comment] 2024-12-06 09:00
The issue is still not working correctly - try selecting multiple namespaces at https://grafana.sandbox.victoriametrics.com/d/be5zidev72m80f/k8s-logs-demo?orgId=1&var-ds=fdmacvu8gcwlce&var-namespace=All&var-pod=All&var-container=All&var-filter=%2A&var-limit=100

**Comment by worker24h** [comment] 2024-12-06 11:56
> The filter is still not working correctly - try selecting multiple namespaces at https://grafana.sandbox.victoriametrics.com/d/be5zidev72m80f/k8s-logs-demo?orgId=1&var-ds=fdmacvu8gcwlce&var-namespace=All&var-pod=All&var-container=All&var-filter=%2A&var-limit=100 

I can't sign in without username and password.  Do you support a capture screen, I will try to fix it. Thanks @hagen1778

**Comment by dmitryk-dk** [comment] 2024-12-06 12:24
Hi @worker24h ! You just fixed one possible problem, but in the filters, there can be another `OR`
<img width="890" alt="Screenshot 2024-12-06 at 13 23 45" src="https://github.com/user-attachments/assets/821d55b4-7df9-45c5-919f-b2a74367d0fc">
<img width="1385" alt="Screenshot 2024-12-06 at 13 23 58" src="https://github.com/user-attachments/assets/91774e3a-248b-4873-81da-3ff05b695e42">

**Comment by Loori-R** [comment] 2024-12-06 12:25
@worker24h, Your code works for the case `{field_name=~"foo|bar"}`, but it doesn’t handle queries like `field_name:~"foo|bar"`.

It’s also necessary to add support for the [in()](https://docs.victoriametrics.com/victorialogs/logsql/#multi-exact-filter) function, for example: `field_name:in(foo,bar)`.

There might be other cases where variables need to be inserted without using `OR`. @hagen1778 or @dmitryk-dk , maybe you have some insights.

We might need a solution more complex than regular expressions. I plan to take a closer look at this issue today.

**Comment by worker24h** [comment] 2024-12-06 13:06
> @worker24h, Your code works for the case `{field_name=~"foo|bar"}`, but it doesn’t handle queries like `field_name:~"foo|bar"`.
> 
> 
> 
> It’s also necessary to add support for the [in()](https://docs.victoriametrics.com/victorialogs/logsql/#multi-exact-filter) function, for example: `field_name:in(foo,bar)`.
> 
> 
> 
> There might be other cases where variables need to be inserted without using `OR`. @hagen1778 or @dmitryk-dk , maybe you have some insights.
> 
> 
> 
> We might need a solution more complex than regular expressions. I plan to take a closer look at this issue today.

OK. I consider that if I can unify all logical ORs into using the keyword `OR`, while the keyword `| ` is only used to express pipeline.

So，it need to modify backend code, **But** this syntax is simple and unified for users, and Loki only has keyword `OR`.

@hagen1778 @dmitryk-dk @Loori-R

**Comment by dmitryk-dk** [comment] 2024-12-10 11:24
Hi! The issue was fixed in the new [release](https://github.com/VictoriaMetrics/victorialogs-datasource/tree/v0.11.0). Please check it. If you find any problems feel free to reopen the issue

**Closed by dmitryk-dk** 2024-12-10 11:24 UTC
Labels: bug, question
