### ISSUE TITLE
bug: VictoriaLogs - missing records (but present in Loki)

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/victorialogs-datasource#91] opened 2024-10-15 13:48 UTC
**Chart name and version**
Helm chart: victoria-logs-single. version: v0.6.3
Docker image: victoriametrics/victoria-logs:v0.35.0-victorialogs
Grafana VictoriaLogs Data source version: 0.5.0

**Describe the bug**
We have a log records with a big `body` field.
They are written to the Loki, but can't be found in VMLogs.

**Loki query**: `{app="backend-api", namespace="prod-backend-api-ns"} |= "b4c2ecd2-000b-46e5-a448-0983963c0688"`
- returns desired records

![image](https://github.com/user-attachments/assets/8e66781d-607d-42aa-a68f-b9f2480bbe28)

**VMlogs query**: `app:="backend-api" namespace:="prod-backend-api-ns" "b4c2ecd2-000b-46e5-a448-0983963c0688"`
- returns noting

![image](https://github.com/user-attachments/assets/05caa98f-3858-46e4-95a0-c0744669078a)

If query by an Amazon X-Ray ID related to the records, then:

**Loki query**: `{app="backend-api", namespace="prod-backend-api-ns"} |= "Root=1-670e6e90-2e398c1005aa39f076ec1428"`
- returns 8 results, including the record with the big `body` field

![image](https://github.com/user-attachments/assets/4e088549-5946-44e5-ab10-d0efc09fde6c)

**VMlogs query**: `app:="backend-api" namespace:="prod-backend-api-ns" "b4c2ecd2-000b-46e5-a448-0983963c0688"`
- returns 7 results, and no record with the big `body` field
![image](https://github.com/user-attachments/assets/9ad4a36e-cc6f-415c-a548-b7bc7957ed2c)

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
  grafana:
    enabled: true
   ...
    env:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "victorialogs-datasource"
    ...
    plugins:
     ...
      - https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.5.0/victorialogs-datasource-v0.5.0.zip;victorialogs-datasource
```

**Comment by AndrewChubatiuk** [comment] 2024-10-15 17:17
transfered issue to victorialogs-datasource as this issue looks like datasource related

**Comment by dmitryk-dk** [comment] 2024-10-15 18:20
Hi @arseny-zinchenko ! Can you share the response you get if you call the victorialogs API ? You can hide sensitive data.

**Comment by hagen1778** [comment] 2024-10-23 09:54
@arseny-zinchenko kindly pinging you regarding https://github.com/VictoriaMetrics/victorialogs-datasource/issues/91#issuecomment-2414711370
We need to understand if this is datasource related or vlogs related problem.

**Comment by dmitryk-dk** [comment] 2024-10-23 10:06
> @arseny-zinchenko kindly pinging you regarding [#91 (comment)](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/91#issuecomment-2414711370) We need to understand if this is datasource related or vlogs related problem.

I got the JSON, will add the test, and check where the problem is. Will write about my investigation soon

**Comment by hagen1778** [comment] 2024-10-25 09:05
https://github.com/VictoriaMetrics/victorialogs-datasource/pull/95 has been merged and will be available in the next release.

**Closed** 2024-10-30 18:15 UTC
Labels: bug, waiting for release
