### ISSUE TITLE
v0.13.1 tarball breaks plugin init

### ISSUE THREAD

**Issue by itmustbejj** [VictoriaMetrics/victorialogs-datasource#177] opened 2024-12-19 17:48 UTC
From my grafana pod:
```
❯ k logs grafana-75dbc794cd-s5nqd -c load-vm-ds-plugin
+ mkdir -p /var/lib/grafana/plugins/
+ curl -s https://api.github.com/repos/VictoriaMetrics/victorialogs-datasource/releases/latest
+ + grephead -oE -1 'v[0-9]+\.[0-9]+\.[0-9]+'

+ ver=v0.13.1
+ curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.1/victorialogs-datasource-v0.13.1.tar.gz -o /var/lib/grafana/plugins/plugin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     50      0 --:--:-- --:--:-- --:--:--    51
+ tar -xf /var/lib/grafana/plugins/plugin.tar.gz -C /var/lib/grafana/plugins/
tar: invalid tar magic
```

I can reproduce it locally:
```
❯ curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.1/victorialogs-datasource-v0.13.1.tar.gz -o plugin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     70      0 --:--:-- --:--:-- --:--:--    70
❯ tar -xf plugin.tar.gz
tar: Error opening archive: Unrecognized archive format

❯ ll
total 8
-rw-r--r--  1 myuser  staff     9B Dec 19 09:46 plugin.tar.gz
```

**Comment by itmustbejj** [comment] 2024-12-19 17:53
Could this be related to the breaking changes in v0.13.0?

**Comment by dmitryk-dk** [comment] 2024-12-19 17:54
Hi @itmustbejj ! Can you try to download tarball now? I have updated them from my local. I suppose the problem is with the github action. need to check

**Comment by itmustbejj** [comment] 2024-12-19 17:55
Ah yes -- looks related to the rename.

It was download `curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.1/victorialogs-datasource-v0.13.1.tar.gz -o plugin.tar.gz`

whereas the link under releases has the filename as `victoriametrics-logs-datasource-v0.13.1.tar.gz`.

**Comment by dmitryk-dk** [comment] 2024-12-19 17:57
> Ah yes -- looks related to the rename.
> 
> It was downloading `curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.1/victorialogs-datasource-v0.13.1.tar.gz -o plugin.tar.gz`
> 
> whereas the link under releases has the filename as `victoriametrics-logs-datasource-v0.13.1.tar.gz`.

Yes, we renamed the all names with the new plugin id. 
If you confirm that everything is ok, i will close the issue

**Closed** 2024-12-19 18:07 UTC

**Comment by itmustbejj** [comment] 2024-12-19 18:31
@dmitryk-dk I can confirm that fixed the issue.
