### ISSUE TITLE
VictoriaLogs has no context view function bug

### ISSUE THREAD

**Issue by chown1987** [VictoriaMetrics/victorialogs-datasource#141] opened 2024-12-06 08:11 UTC
VictoriaLogs has no context view function bug

**Comment by dmitryk-dk** [comment] 2024-12-06 08:12
Hi @chown1987 ! Your issue is a duplicate of the https://github.com/VictoriaMetrics/victorialogs-datasource/issues/41. I close this issue please see the progress in the mentioned issue

**Closed by dmitryk-dk** 2024-12-06 08:12 UTC
