### ISSUE TITLE
Error when using `fields` pipe

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/victorialogs-datasource#23] opened 2024-05-20 15:02 UTC
To reproduce try using the following query: `_time:10h * | unpack_json from _msg | fields level`

The following error is displayed in UI when using the `fields` selector:
> Query error
> An error occurred within the plugin

Grafana logs:
```
grafana logger=context userId=4 orgId=1 uname=z.bessarab@victoriametrics.com t=2024-05-20T14:59:34.689886559Z level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to query data: Failed to query data: rpc error: code = Unknown desc = frame has different field lengths, field 0 is len 0 b
ut field 2 is len 1000" remote_addr=95.217.16.43 traceID=
grafana logger=context userId=4 orgId=1 uname=z.bessarab@victoriametrics.com t=2024-05-20T14:59:34.690327282Z level=error msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=95.217.16.43 time_ms=56 duration=56.145455ms size=116 referer="https://grafana.sandbox.victoriametrics.com/explore?orgId
=1&panes=%7B%229y4%22%3A%7B%22datasource%22%3A%22fdmacvu8gcwlce%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22victorialogs-datasource%22%2C%22uid%22%3A%22fdmacvu8gcwlce%22%7D%2C%22expr%22%3A%22_time%3A10h+%2A+%7C+unpack_json+from+_msg+%7C+fields+level%22%2C%22queryType%22%3A%2
2range%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&schemaVersion=1" handler=/api/ds/query status_source=downstream
```

**Comment by Loori-R** [comment] 2024-06-18 13:57
@dk, can you take a look? 
I think the error occurs because the logs are missing `_time`, `_msg`, and `_stream`, and the entry looks something like `{"level":""}`.

**Comment by dk** [comment] 2024-06-18 13:59
Sure thing. Looks like the problem is EWRONGDK 🤣

**Comment by Loori-R** [comment] 2024-06-18 14:05
Oops, sorry :sweat_smile:. I meant @dmitryk-dk

**Comment by dmitryk-dk** [comment] 2024-06-20 11:47
Yeah, i will check it. What to fix some bugs for the datasource

**Comment by dmitryk-dk** [comment] 2024-06-25 14:01
Hi @zekker6 ! Issue was fixed in the [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.2.2). Close as resolved

**Closed by dmitryk-dk** 2024-06-25 14:01 UTC
Labels: bug, waiting for release
